spring:
  application:
    name: RATING-APP-CONFIG-SERVER-PROD

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
  client:
    fetch-registry: true
    register-with-eureka: true
    
    service-url:
      defaultZone: http://localhost:8761/eureka
